# /wordpress-docker/docker-compose.yml
---
version: '3.8'
networks:
  wpnet: {}
services:
  db:
    container_name: 'local-wordpress-db'
    image: 'mysql:5.7'
    volumes:
      - './.container/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    networks:
      - wpnet
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  wordpress:
    container_name: 'local-wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '8080:80'
    networks:
      - wpnet
    environment:
      WORDPRESS_DB_HOST: 'db'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DEBUG: 1
    volumes:
      - "./.container/wordpress:/var/www/html"
      - "./:/var/www/html/wp-content/plugins/ast-template-view:Z"
