apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  containers:
  - name: wpdb
    image: docker.io/library/mariadb:10
    volumeMounts:
    - mountPath: /var/lib/mysql/
      name: mysql_data-pvc
    ports:
      - containerPort: 3306
        hostPort: 13306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: somewordpress
      - name: MYSQL_DATABASE
        value: wordpress_db
      - name: MYSQL_USER
        value: wordpress_user
      - name: MYSQL_PASSWORD
        value: wordpress_password
    tty: true
  - name: wp
    image: docker.io/library/wordpress:latest
    volumeMounts:
    - mountPath: /var/www/html/wp-content/plugins/ast-template-view:Z
      name: wp-plugin-pvc
    env:
      - name: WORDPRESS_DB_HOST
        value: 127.0.0.1:3306
      - name: WORDPRESS_DB_NAME
        value: wordpress_db
      - name: WORDPRESS_DB_USER
        value: wordpress_user
      - name: WORDPRESS_DB_PASSWORD
        value: wordpress_password
      - name: WORDPRESS_DEBUG
        value: "1"
    ports:
      - containerPort: 80
        hostPort: 8080
    tty: true
  restartPolicy: OnFailure
  volumes:
  - name: mysql_data-pvc
    persistentVolumeClaim:
      claimName: mysql_data
  - name: wp-plugin-pvc
    hostPath:
      path: "/home/mzalewsk/sources/ast-template-view/"
